### PR TITLE
Repository Overhaul

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Add Tags**
  - `raft`
  - `mod`
  - `minimap`

  <br>

- **Update Description**

  `Raft mod adding a minimap.`

  <br>

- ***[Disable unused Widgets][Widgets]***:

  - `Packages`

  <br>

- ***[Disable unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`

  - `Wiki`
  
  <br>

<br>
<br>

## ![Badge Changes]

- Added missing license copy

- Added editorconfig

- formatted manifest

- Ported README

- General formatting / spacing

- Added image previews

- Added license / requirements badges

- Added quicklink

- Linked game

- Added marker visualization

- Added social contact buttons

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## ![Badge Robot]

<kbd> <br>            No, I'm not a robot.            <br> </kbd>

<kbd> <br>    Yes, you are not the first.    <br> </kbd>

<kbd> <br>     I just made a PR template.     <br> </kbd>

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/Minimap

### CODE REVIEW

**Comment by Whitebrim** [comment]
It's great, I didn't add readme because this repo is not main page for this mod, it's just source code and meant to be accessible only from https://www.raftmodding.com/mods/minimap, not from git search...

**Comment by ElectronicsArchiver** [comment]
A GitHub repo of a project is the main page for a whole variety of people though~

It's where the project is actually at, where change happens, with many tools, options and information, unlike the raftmodding page or in general things like nexusmods.

**Comment by ElectronicsArchiver** [comment]
It also helps people find your mod to begin with~

**Comment by Whitebrim** [comment]
> It also helps people find your mod to begin with~

https://www.google.com/search?q=raft+minimap&oq=raft+minimap

**Comment by ElectronicsArchiver** [comment]
> > It also helps people find your mod to begin with~
> 
> https://www.google.com/search?q=raft+minimap&oq=raft+minimap

? How does that change what I said

more SEO = better
This way, people can find you on GitHub better as well

**Comment by Whitebrim** [comment]
It would be great, if this work would have been done on my more popular repositories, not a godforsaken raft mod
https://github.com/Whitebrim/AnimatedSprite

**Comment by ElectronicsArchiver** [comment]
I do formatting work on any kind of repo~

**Comment by ElectronicsArchiver** [comment]
From LinuxCNC, Atom, JascoProducts to SCP:AdminToolbox to Hotdog

**Review by Whitebrim — CHANGES_REQUESTED** [review]
This is wierd formatting that I'm not agree with:
`spaces between " and ,`
`},{`
`lines start with spaces and tab randomly.`

Run through any online `json beautifier` and then I'll merge pr

**Review by Whitebrim — APPROVED** [review]

**Comment by ElectronicsArchiver** [comment]
Thanks~

**Pull request merged**
